### ISSUE TITLE
The Invert feature does not cope with the selected voices

### ISSUE THREAD

**Issue by lgvr123** [Ash-86/Pitch-and-Rhythm-Transformer#2]
If, in a 2 voices part, one selects only the second voice and try applying an Invert action on that selection, the voice 2 is not modified but the (non-selected) voice 1 is erroneously altered.

![InvertWrongVoice](https://github.com/Ash-86/Pitch-and-Rhythm-Transformer/assets/50494/c654e25c-0f75-4936-943a-02748dae0da5)

Tested in MuseScore 3.7/4.2.1 Windows10

**Comment by Ash-86** [comment]
The plugin currently transforms all voices within the selection regardless of selection filter. (in your example, notice that both voices are inverted). That said,  applying transformation to selected voices only  would indeed be a nice feature to have.  Will work on it ass soon as i have some spare time.

**Comment by Ash-86** [comment]
Turns out it was an easy fix. Just pushed the new feature. Plugin should now respect the selection filter. let me know in case of other issues. 
Cheers!

**Comment by lgvr123** [comment]
Cool! I'll try this soon.
